# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/updating/#never-change-the-answers-file-manually
_commit: v2.0.2
_src_path: gh:FallingColors/hexdummy
advanced: true
capitalize_platforms: false
classname: HexClone
default_branch: main
description: HexClone addon for Hex Casting
display_name: HexClone
github_repo: HexCloneAddon
github_user: Glorken
homepage_url: https://www.cass.gay/HexCloneAddon
java_package: gay.cass.hexclone
kotlin_package: gay.cass.hexclone
mappings_name: Mojmap
minecraft_version_in_mod_version: true
mod_version: 0.1.0
modid: hexclone
sources_url: https://github.com/Glorken/HexCloneAddon
